### ISSUE TITLE
0.7.0 需求收集

### ISSUE THREAD

**Issue by sorrycc** [ant-tool/atool-build#104]
- [ ] 升级到 webpack2, #64 (需进一步调研)
- [x] 调整 babel presets 和 plugin 引入方式, #112 
- [ ] 调整 config 扩展方式，#114

**Comment by sorrycc** [comment]
通过 milestore 管理了。
