### ISSUE TITLE
atool-build@1.0 实现细分

### ISSUE THREAD

**Issue by pigcan** [ant-tool/atool-build#298]
atool-build@1.0 架构图

![atool-build@1.0](https://camo.githubusercontent.com/cd1a0ec311f58fbe10e019cd9bca442527bcc9d7/68747470733a2f2f7a6f732e616c697061796f626a656374732e636f6d2f726d73706f7274616c2f6b774f534d546c646d704977564567665a5843682e706e67)

------

### 核心功能点

> extends-system

- [ ] 配置的可扩展系统，关联 issue #293

> feature-block-system

- [ ] 从配置到 webpack 真实配置的转换系统， 关联 issue #294

> validator-system

- [ ] 校验系统， 关联 issue #295

> bin

- [ ] atool-build bin ， 关联 issue #296

### 运营

- [ ] 新版文档中心，配套配置 demo 集合  issue #297
