### ISSUE TITLE
0.6.0 需求收集

### ISSUE THREAD

**Issue by sorrycc** [ant-tool/atool-build#61]
## 改进

- [x] 构建日志不输出 uglifyjs 的 warning 信息，#50
- [x] 修改 babel 和 UglifyJsPluginConfig 配置更简单，直接通过 `webpackConfig.babel` 调用，#58
- [x] js 里 require 的 html 文件会被复制到输出目录，#53
- [x] 通过匹配 `*.module.css` 支持 `css-modules`，一种更好的 css 组织方式
- [x] 添加 NoErrorsPlugin 插件，构建出错时不生成文件
- [x] 支持 rucksack，详见 http://simplaio.github.io/rucksack/
- [x] 支持 webpackConfig 处理了 i18n 后是数组的场景，#98
- [x] watch 模式下精简日志信息，#86
- [x] 支持 decorator，#65

## 其他

- [x] test runner 改用 mocha
- [x] 去除 object-assign 依赖，改用 `...`

**Comment by pigcan** [comment]
目前给 `autoprefixer` https://github.com/ant-tool/atool-build/blob/master/src/getWebpackCommonConfig.js#L97 增加参数也非常不便利，现在 `postcss`  只有一个插件还好解决， 但是很难保证以后有多个且顺序会发生变更 .

目前我在覆盖上的解决方案是 http://ant-tool.github.io/spm-to-atool-build.html#spmautoprefixer 很麻烦 - -！

**Comment by silentcloud** [comment]
改用 mocha 我年后来搞

**Comment by sorrycc** [comment]
`css-modules` 通过匹配 `.module.css` 支持。
